name: Update Google Sheet with Stocktwits Trending Stocks

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  update-sheet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          
      - name: Install required packages for headless chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            wget \
            curl \
            unzip \
            libxss1 \
            libappindicator3-1 \
            libgdk-pixbuf2.0-0 \
            libnss3 \
            libgbm1 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libx11-xcb1 \
            libsecret-1-0 \
            libxcomposite1 \
            libxrandr2 \
            libasound2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread google-auth requests beautifulsoup4 selenium webdriver-manager

      - name: Run update script
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: python stocktwits_to_sheets.py
