name: Update Google Sheet with Stocktwits Trending Stocks

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  update-stocks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
  
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium beautifulsoup4 requests
  
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
  
    - name: Set up chromedriver and chrome
      run: |
        sudo rm -f /usr/bin/chromedriver
        sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
        echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV
        echo "CHROMEDRIVER_PATH=/usr/lib/chromium-browser/chromedriver" >> $GITHUB_ENV
  
    - name: Run StockTwits Scraper
      run: python stocktwits_scraper.py 1
