name: Update Google Sheet with Stocktwits Trending Stocks

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  update-stocks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
  
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium beautifulsoup4 requests
  
    - name: Install Chromium and Chromedriver
      run: |
        # Install chromium-browser if not already installed
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        # Check if chromium-chromedriver is installed
        sudo apt-get install -y chromium-chromedriver
  
        # Check if chromedriver exists in the default location
        if [ ! -f /usr/bin/chromedriver ]; then
          echo "Chromedriver not found at /usr/bin/chromedriver. Downloading manually."
          
          # Check Chromium version to match with the appropriate Chromedriver version
          CHROMIUM_VERSION=$(chromium-browser --version | awk '{print $2}' | cut -d. -f1-3)
          echo "Detected Chromium version: $CHROMIUM_VERSION"
          
          # Download the appropriate version of Chromedriver
          DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROMIUM_VERSION)
          echo "Downloading Chromedriver version: $DRIVER_VERSION"
          
          # Download and install chromedriver
          wget https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver
          rm chromedriver_linux64.zip
        fi
  
        # Set the necessary environment variables for Chrome
        echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV
        echo "CHROMEDRIVER_PATH=/usr/bin/chromedriver" >> $GITHUB_ENV
  
    - name: Debug Chromedriver Path
      run: |
        # Print locations of chromium-browser and chromedriver
        echo "Checking chromedriver and chromium-browser paths"
        which chromium-browser
        which chromedriver
        # List the chromedriver binary location
        ls -l /usr/bin/chromedriver
        # Check the location of chromedriver inside the Chromium directory
        ls -l /usr/lib/chromium-browser/
  
    - name: Run StockTwits Scraper
      run: python stocktwits_scraper.py 1
